const templateCard = document.querySelector(".templatecard");
const resultBox = document.querySelector(".searchresult")
const searchBar = document.querySelector("#searchbar")

let cars = []

searchBar.addEventListener("input", (e) => {
    const value = e?.target?.value?.toLowerCase()
    cars.forEach(car => {
        const isVisible = car?.name?.toLowerCase()?.includes(value)
        car.element.classList.toggle("hide", isVisible)
    })
    const allCards = document.querySelector(".searchresult");
    if(e?.target?.value?.length === 0){   
        allCards.style.display = "none"    
    }else{
        allCards.style.display = "flex" 
    }
})



const data = [
    { name: 'Maruti Suzuki Swift' },
    { name: 'Maruti Suzuki Alto' },
    { name: 'Hyundai Creta' },
    { name: 'Hyundai i20' },
    { name: 'Maruti Suzuki Baleno' },
    { name: 'Kia Seltos' },
    { name: 'Hyundai Venue' },
    { name: 'Tata Nexon' },
    { name: 'Mahindra Scorpio' },
    { name: 'Mahindra XUV300' },
    { name: 'Mahindra Bolero' },
    { name: 'Ford EcoSport' },
    { name: 'Toyota Innova Crysta' },
    { name: 'Maruti Suzuki Vitara Brezza' },
    { name: 'Tata Altroz' },
    { name: 'Volkswagen Polo' },
    { name: 'Honda City' },
    { name: 'Hyundai Verna' },
    { name: 'Toyota Fortuner' },
    { name: 'Mahindra Thar' },
    { name: 'Renault Kwid' },
    { name: 'Maruti Suzuki Wagon R' },
    { name: 'Honda Amaze' },
    { name: 'Mahindra XUV500' },
    { name: 'Ford Figo' },
    { name: 'Maruti Suzuki Dzire' },
    { name: 'Hyundai Grand i10 Nios' },
    { name: 'Volkswagen Vento' },
    { name: 'Tata Tiago' },
    { name: 'Skoda Rapid' },
    { name: 'Renault Triber' },
    { name: 'Kia Sonet' },
    { name: 'Mahindra Marazzo' },
    { name: 'Nissan Magnite' },
    { name: 'Maruti Suzuki S-Cross' },
    { name: 'Hyundai Aura' },
    { name: 'Mahindra KUV100 NXT' },
    { name: 'Tata Harrier' },
    { name: 'Toyota Glanza' },
    { name: 'Ford Aspire' },
    { name: 'Honda WR-V' },
    { name: 'Volkswagen Taigun' },
    { name: 'Renault Duster' },
    { name: 'Kia Carnival' },
    { name: 'Maruti Suzuki Ertiga' },
    { name: 'Hyundai Santro' },
    { name: 'Tata Safari' },
    { name: 'Toyota Camry' },
    { name: 'Honda Accord' },
    { name: 'Ford Fusion' },
    { name: 'Chevrolet Malibu' },
    { name: 'Nissan Altima' },
    { name: 'BMW 3 Series' },
    { name: 'Mercedes-Benz C-Class' },
    { name: 'Audi A4' },
    { name: 'Volkswagen Jetta' },
    { name: 'Tesla Model 3' },
    { name: 'Hyundai Sonata' },
    { name: 'Kia Optima' },
    { name: 'Subaru Legacy' },
    { name: 'Mazda Mazda6' },
    { name: 'Lexus ES' },
    { name: 'Acura TLX' },
    { name: 'Infiniti Q50' },
    { name: 'Porsche Panamera' },
    { name: 'Jaguar XE' },
    { name: 'Land Rover Range Rover Evoque' },
    { name: 'Volvo S60' },
    { name: 'Ferrari 488 GTB' },
    { name: 'Lamborghini Huracan' },
    { name: 'Maserati Ghibli' },
    { name: 'Bugatti Chiron' },
    { name: 'McLaren 720S' },
    { name: 'Bentley Continental GT' },
    { name: 'Rolls-Royce Ghost' },
    { name: 'Aston Martin DB11' },
    { name: 'Lotus Evora' },
    { name: 'Alfa Romeo Giulia' },
    { name: 'Genesis G80' },
    { name: 'Lincoln MKZ' },
    { name: 'Buick Regal' },
    { name: 'Cadillac CT5' },
    { name: 'GMC Acadia' },
    { name: 'Jeep Grand Cherokee' },
    { name: 'RAM 1500' },
    { name: 'Chrysler 300' },
    { name: 'Dodge Charger' },
    { name: 'Mitsubishi Outlander' },
    { name: 'Suzuki Kizashi' },
    { name: 'Smart EQ Fortwo' },
    { name: 'Fiat 500X' },
    { name: 'Mini Cooper Countryman' },
    { name: 'Scion tC' },
    { name: 'Hummer H3' },
    { name: 'Saab 9-5' },
    { name: 'Volvo XC90' },
    { name: 'Ford Explorer' },
    { name: 'Honda CR-V' },
    { name: 'Toyota RAV4' },
    { name: 'Nissan Rogue' },
    { name: 'Subaru Forester' },
    { name: 'Hyundai Santa Fe' },
    { name: 'Kia Sorento' },
    { name: 'Mazda CX-5' },
    { name: 'Audi Q5' },
    { name: 'BMW X3' },
    { name: 'Mercedes-Benz GLC' },
    { name: 'Lexus RX' },
    { name: 'Acura RDX' },
    { name: 'Infiniti QX50' },
    { name: 'Porsche Macan' },
    { name: 'Land Rover Discovery Sport' },
    { name: 'Jaguar F-Pace' },
    { name: 'Volvo XC60' },
    { name: 'Ford F-150' },
    { name: 'Chevrolet Silverado 1500' },
    { name: 'GMC Sierra 1500' },
    { name: 'RAM 1500 Classic' },
    { name: 'Toyota Tacoma' },
    { name: 'Nissan Frontier' },
    { name: 'Honda Ridgeline' },
    { name: 'Jeep Gladiator' },
    { name: 'Ford Ranger' },
    { name: 'Chevrolet Colorado' },
    { name: 'GMC Canyon' },
    { name: 'RAM 2500' },
    { name: 'Toyota Tundra' },
    { name: 'Nissan Titan' },
    { name: 'Ford Mustang' },
    { name: 'Chevrolet Camaro' },
    { name: 'Dodge Challenger' },
    { name: 'Chevrolet Corvette' },
    { name: 'Ford GT' },
    { name: 'Acura NSX' },
    { name: 'Porsche 911' },
    { name: 'Nissan GT-R' },
    { name: 'Audi R8' },
    { name: 'BMW i8' },
    { name: 'Mercedes-AMG GT' },
    { name: 'Honda CB Shine' },
    { name: 'TVS Apache' },
    { name: 'Yamaha FZ' },
    { name: 'Hero Splendor' },
    { name: 'Suzuki Access' },
    { name: 'Royal Enfield Classic' },
    { name: 'KTM Duke' },
    { name: 'Harley-Davidson Street' },
    { name: 'Kawasaki Ninja' },
    { name: 'Ducati Monster' },
    { name: 'BMW S1000RR' },
    { name: 'Triumph Bonneville' },
    { name: 'Aprilia SR 150' },
    { name: 'Mahindra Mojo' },
    { name: 'Hyosung GT250R' },
    { name: 'Benelli TNT 300' },
    { name: 'Indian Scout' },
    { name: 'MV Agusta Brutale' },
    { name: 'Ducati Panigale' },
    { name: 'Honda CBR' },
    { name: 'Bajaj Dominar' },
    { name: 'TVS Jupiter' },
    { name: 'Yamaha R15' },
    { name: 'Hero Passion' },
    { name: 'Suzuki Gixxer' },
    { name: 'Royal Enfield Bullet' },
    { name: 'KTM RC' },
    { name: 'Harley-Davidson Fat Boy' },
    { name: 'Kawasaki Versys' },
    { name: 'Ducati Multistrada' },
    { name: 'BMW R1250GS' },
    { name: 'Triumph Street Triple' },
    { name: 'Aprilia Tuono' },
    { name: 'Mahindra Centuro' },
    { name: 'Hyosung Aquila' },
    { name: 'Benelli Leoncino' },
    { name: 'Indian Chief' },
    { name: 'MV Agusta F3' },
    { name: 'Ducati Diavel' },
    { name: 'Honda CB Unicorn' },
    { name: 'Bajaj Avenger' },
    { name: 'TVS Apache RR' },
    { name: 'Yamaha MT' },
    { name: 'Hero HF Deluxe' },
    { name: 'Suzuki Hayabusa' },
    { name: 'Royal Enfield Himalayan' },
    { name: 'KTM Adventure' },
    { name: 'Harley-Davidson Iron' },
    { name: 'Kawasaki Z' },
    { name: 'Ducati Hypermotard' },
    { name: 'BMW G310R' },
    { name: 'Triumph Tiger' },
    { name: 'Aprilia RS' },
    { name: 'Mahindra Gusto' },
    { name: 'Hyosung GD250R' },
    { name: 'Benelli TNT 600i' },
    { name: 'Indian Chieftain' },
    { name: 'MV Agusta Rivale' },
    { name: 'Ducati Scrambler' },
    { name: 'Honda Dio' },
    { name: 'Bajaj Platina' },
    { name: 'TVS Star City' },
    { name: 'Yamaha Fazer' },
    { name: 'Hero Glamour' },
    { name: 'Suzuki Intruder' },
    { name: 'Royal Enfield Thunderbird' },
    { name: 'KTM Adventure' },
    { name: 'Harley-Davidson Sportster' },
    { name: 'Kawasaki W' },
    { name: 'Ducati Streetfighter' },
    { name: 'BMW R nineT' },
    { name: 'Triumph Daytona' },
    { name: 'Aprilia SR' },
    { name: 'Mahindra Pantero' },
    { name: 'Hyosung Aquila' },
    { name: 'Benelli TNT 150' },
    { name: 'Indian Roadmaster' },
    { name: 'MV Agusta Turismo Veloce' },
    { name: 'Ducati 899 Panigale' },
    { name: 'Honda Livo' },
    { name: 'Bajaj CT' },
    { name: 'TVS Radeon' },
    { name: 'Yamaha Saluto' },
    { name: 'Hero Xtreme' },
    { name: 'Suzuki Burgman' },
    { name: 'Royal Enfield Continental' },
    { name: 'KTM Super Duke' },
    { name: 'Harley-Davidson Dyna' },
    { name: 'Kawasaki Vulcan' },
    { name: 'Ducati SuperSport' },
    { name: 'BMW F750GS' },
    { name: 'Triumph Rocket' },
    { name: 'Aprilia Shiver' },
    { name: 'Mahindra Pantero' },
    { name: 'Hyosung Aquila' },
    { name: 'Benelli TNT 150' },
    { name: 'Indian Roadmaster' },
    { name: 'MV Agusta Turismo Veloce' },
    { name: 'Ducati 899 Panigale' },
    { name: 'Honda Livo' },
    { name: 'Bajaj CT' },
    { name: 'TVS Radeon' },
    { name: 'Yamaha Saluto' },
    { name: 'Hero Xtreme' },
    { name: 'Suzuki Burgman' },
    { name: 'Royal Enfield Continental' },
    { name: 'KTM Super Duke' },
    { name: 'Harley-Davidson Dyna' },
    { name: 'Kawasaki Vulcan' },
    { name: 'Ducati SuperSport' },
    { name: 'BMW F750GS' },
    { name: 'Triumph Rocket' },
    { name: 'Aprilia Shiver' },
    { name: 'Hero Splendor' },
    { name: 'Hero HF Deluxe' },
    { name: 'Bajaj Pulsar' },
    { name: 'TVS Apache' },
    { name: 'Honda Activa' },
    { name: 'Hero Glamour' },
    { name: 'Royal Enfield Classic' },
    { name: 'Honda CB Shine' },
    { name: 'Bajaj Platina' },
    { name: 'TVS Jupiter' },
    { name: 'Suzuki Access' },
    { name: 'Yamaha FZ' },
    { name: 'Royal Enfield Bullet' },
    { name: 'Honda Dio' },
    { name: 'Bajaj CT' },
    { name: 'TVS Star City' },
    { name: 'Yamaha YZF R15' },
    { name: 'Suzuki Gixxer' },
    { name: 'Bajaj Dominar' },
    { name: 'KTM Duke' },
    { name: 'Hero Passion' },
    { name: 'Honda Unicorn' },
    { name: 'Yamaha MT 15' },
    { name: 'Royal Enfield Himalayan' },
    { name: 'Bajaj Avenger' },
    { name: 'TVS Apache RR' },
    { name: 'KTM RC' },
    { name: 'Hero Xpulse' },
    { name: 'Honda Livo' },
    { name: 'Yamaha Fazer' },
    { name: 'Suzuki Burgman Street' },
    { name: 'Bajaj Discover' },
    { name: 'Hero Super Splendor' },
    { name: 'TVS NTorq' },
    { name: 'Yamaha R3' },
    { name: 'Royal Enfield Interceptor 650' },
    { name: 'Bajaj V' },
    { name: 'Hero Xtreme 160R' },
    { name: 'TVS Apache RTR 160' },
    { name: 'Yamaha Fascino' },
    { name: 'Suzuki Hayabusa' },
    { name: 'Bajaj Chetak' },
    { name: 'Hero Maestro Edge' },
    { name: 'Honda Hornet' },
    { name: 'KTM Adventure' },
    { name: 'Royal Enfield Thunderbird' },
    { name: 'Bajaj NS' },
    { name: 'Hero Karizma' },
];

cars = data.map(car => {

    const card = templateCard.content.cloneNode(true).children[0];
    const contentInfo = card.querySelector(".card p")
    contentInfo.textContent = car?.name
    resultBox.appendChild(card)

    return {name: car?.name, element: card}
    
})
